spring.application.name=orchestrator-service
spring.application.name=orchestrator-service
server.port=8080

# Use the keys defined in your .env file
google.oauth.client-id=${GOOGLE_CLIENT_ID}
google.oauth.client-secret=${GOOGLE_CLIENT_SECRET}
google.jwt.secret=${GOOGLE_JWT_SECRET}